/* ============================================================================
   00_setup.sql — database, schemas, personas, warehouse, stages
   CareLens 360. Synthetic data only.
============================================================================ */
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS CARELENS_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  COMMENT = 'CareLens 360 compute';

CREATE DATABASE IF NOT EXISTS CARELENS
  COMMENT = 'Patient/Member 360 + clinical-regulatory document copilot. FULLY SYNTHETIC DATA.';

CREATE SCHEMA IF NOT EXISTS CARELENS.RAW        COMMENT = 'Landing zone';
CREATE SCHEMA IF NOT EXISTS CARELENS.CURATED    COMMENT = 'Conformed clinical + claims + documents';
CREATE SCHEMA IF NOT EXISTS CARELENS.GOLD       COMMENT = '360 records, transparent risk, evidence ledger';
CREATE SCHEMA IF NOT EXISTS CARELENS.AI         COMMENT = 'Semantic view, search services, agent';
CREATE SCHEMA IF NOT EXISTS CARELENS.GOVERNANCE COMMENT = 'Policies, tags, audit';
CREATE SCHEMA IF NOT EXISTS CARELENS.EVAL       COMMENT = 'Golden questions + grounding harness';

/* ---- personas: deliberately different entitlement, not cosmetic ---------- */
CREATE ROLE IF NOT EXISTS CARELENS_ADMIN;
CREATE ROLE IF NOT EXISTS CARELENS_CLINICIAN COMMENT = 'Full PHI, own clinic panel only';
CREATE ROLE IF NOT EXISTS CARELENS_CARE_MGR  COMMENT = 'Partial masking, entitled clinics';
CREATE ROLE IF NOT EXISTS CARELENS_ANALYST   COMMENT = 'De-identified, no clinical narrative';

GRANT ROLE CARELENS_ADMIN TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE CARELENS_WH TO ROLE CARELENS_ADMIN;
GRANT USAGE ON WAREHOUSE CARELENS_WH TO ROLE CARELENS_CLINICIAN;
GRANT USAGE ON WAREHOUSE CARELENS_WH TO ROLE CARELENS_CARE_MGR;
GRANT USAGE ON WAREHOUSE CARELENS_WH TO ROLE CARELENS_ANALYST;
GRANT ALL ON DATABASE CARELENS TO ROLE CARELENS_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE CARELENS TO ROLE CARELENS_ADMIN;

GRANT USAGE ON DATABASE CARELENS TO ROLE CARELENS_CLINICIAN;
GRANT USAGE ON DATABASE CARELENS TO ROLE CARELENS_CARE_MGR;
GRANT USAGE ON DATABASE CARELENS TO ROLE CARELENS_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CARELENS TO ROLE CARELENS_CLINICIAN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CARELENS TO ROLE CARELENS_CARE_MGR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CARELENS TO ROLE CARELENS_ANALYST;

USE ROLE CARELENS_ADMIN; USE WAREHOUSE CARELENS_WH; USE DATABASE CARELENS;

/* ---- stages -------------------------------------------------------------- */
CREATE STAGE IF NOT EXISTS RAW.STRUCTURED_STAGE
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Synthetic EHR/claims CSV extracts';

CREATE STAGE IF NOT EXISTS RAW.DOC_STAGE
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Synthetic clinical + regulatory documents';

CREATE STAGE IF NOT EXISTS AI.STREAMLIT_STAGE
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_HEADER
  TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('','NULL') EMPTY_FIELD_AS_NULL = TRUE;

/* whole-file read: control-char delimiters so a markdown file lands in one field */
CREATE FILE FORMAT IF NOT EXISTS RAW.WHOLE_FILE_TEXT
  TYPE = CSV FIELD_DELIMITER = '\x01' RECORD_DELIMITER = '\x02'
  SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = NONE;

/* ---- provenance tag: never removed -------------------------------------- */
CREATE TAG IF NOT EXISTS GOVERNANCE.SYNTHETIC_DATA_FLAG
  COMMENT = 'TRUE means the object contains only machine-generated non-personal data';
CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_SENSITIVITY
  ALLOWED_VALUES 'DIRECT_IDENTIFIER','QUASI_IDENTIFIER','CLINICAL','FINANCIAL','NON_SENSITIVE';

ALTER SCHEMA CARELENS.CURATED SET TAG GOVERNANCE.SYNTHETIC_DATA_FLAG = 'TRUE';
ALTER SCHEMA CARELENS.GOLD    SET TAG GOVERNANCE.SYNTHETIC_DATA_FLAG = 'TRUE';

SELECT 'setup complete' AS status;
