/* ============================================================================
   06_governance.sql — tags, masking, row access, audit log
   Policies evaluate at query time under the caller's role, so the agent
   inherits entitlement instead of reimplementing it.
============================================================================ */
USE ROLE CARELENS_ADMIN; USE WAREHOUSE CARELENS_WH; USE DATABASE CARELENS; USE SCHEMA GOVERNANCE;

/* ---- who can see which clinic. entitlement table, not hardcoded roles --- */
CREATE OR REPLACE TABLE CLINIC_ENTITLEMENT (role_name STRING, attributed_clinic STRING);
INSERT INTO CLINIC_ENTITLEMENT VALUES
  ('CARELENS_CLINICIAN','FVMG-NORTH'),
  ('CARELENS_CLINICIAN','FVMG-SOUTH'),
  ('CARELENS_CARE_MGR','FVMG-NORTH'),
  ('CARELENS_CARE_MGR','FVMG-SOUTH'),
  ('CARELENS_CARE_MGR','PRIME-PRIMARY'),
  ('CARELENS_CARE_MGR','RIVERBEND');

/* ---- masking. IS_ROLE_IN_SESSION so role hierarchies resolve properly --- */
CREATE OR REPLACE MASKING POLICY MP_NAME AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARELENS_ADMIN') OR IS_ROLE_IN_SESSION('CARELENS_CLINICIAN') THEN val
    WHEN IS_ROLE_IN_SESSION('CARELENS_CARE_MGR') THEN LEFT(val,1) || '*** ' || SPLIT_PART(val,' ',-1)
    ELSE '***REDACTED***'
  END;

CREATE OR REPLACE MASKING POLICY MP_DOB AS (val DATE) RETURNS DATE ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARELENS_ADMIN') OR IS_ROLE_IN_SESSION('CARELENS_CLINICIAN') THEN val
    ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)   -- generalise to year of birth
  END;

CREATE OR REPLACE MASKING POLICY MP_POSTAL AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARELENS_ADMIN') OR IS_ROLE_IN_SESSION('CARELENS_CLINICIAN') THEN val
    ELSE LEFT(val,3) || 'XX'
  END;

/* free-text clinical narrative is the easiest thing here to re-identify
   someone from, and the analyst role has no need for it */
CREATE OR REPLACE MASKING POLICY MP_CLINICAL_TEXT AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CARELENS_ADMIN')
      OR IS_ROLE_IN_SESSION('CARELENS_CLINICIAN')
      OR IS_ROLE_IN_SESSION('CARELENS_CARE_MGR') THEN val
    ELSE '***CLINICAL NARRATIVE WITHHELD FOR THIS ROLE***'
  END;

CREATE OR REPLACE ROW ACCESS POLICY RAP_CLINIC_PANEL AS (clinic STRING) RETURNS BOOLEAN ->
  IS_ROLE_IN_SESSION('CARELENS_ADMIN')
  OR IS_ROLE_IN_SESSION('CARELENS_ANALYST')          -- all rows, but masked columns
  OR EXISTS (SELECT 1 FROM CARELENS.GOVERNANCE.CLINIC_ENTITLEMENT e
             WHERE e.attributed_clinic = clinic AND IS_ROLE_IN_SESSION(e.role_name));

/* ---- bind ---------------------------------------------------------------- */
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN full_name   SET MASKING POLICY MP_NAME;
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN first_name  SET MASKING POLICY MP_NAME;
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN last_name   SET MASKING POLICY MP_NAME;
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN birth_date  SET MASKING POLICY MP_DOB;
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN postal_code SET MASKING POLICY MP_POSTAL;
ALTER TABLE CARELENS.CURATED.DIM_PATIENT MODIFY COLUMN full_name   SET MASKING POLICY MP_NAME;
ALTER TABLE CARELENS.CURATED.DIM_PATIENT MODIFY COLUMN birth_date  SET MASKING POLICY MP_DOB;
ALTER TABLE CARELENS.CURATED.DIM_PATIENT MODIFY COLUMN postal_code SET MASKING POLICY MP_POSTAL;
ALTER TABLE CARELENS.CURATED.DOC_CHUNK MODIFY COLUMN chunk_text SET MASKING POLICY MP_CLINICAL_TEXT;

ALTER TABLE CARELENS.GOLD.PATIENT_360      ADD ROW ACCESS POLICY RAP_CLINIC_PANEL ON (attributed_clinic);
ALTER TABLE CARELENS.GOLD.RISK_READMISSION ADD ROW ACCESS POLICY RAP_CLINIC_PANEL ON (attributed_clinic);
ALTER TABLE CARELENS.GOLD.CARE_GAP         ADD ROW ACCESS POLICY RAP_CLINIC_PANEL ON (attributed_clinic);

/* ---- sensitivity tags --------------------------------------------------- */
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN full_name   SET TAG DATA_SENSITIVITY = 'DIRECT_IDENTIFIER';
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN birth_date  SET TAG DATA_SENSITIVITY = 'QUASI_IDENTIFIER';
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN postal_code SET TAG DATA_SENSITIVITY = 'QUASI_IDENTIFIER';
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN latest_a1c  SET TAG DATA_SENSITIVITY = 'CLINICAL';
ALTER TABLE CARELENS.GOLD.PATIENT_360 MODIFY COLUMN total_allowed_amount SET TAG DATA_SENSITIVITY = 'FINANCIAL';

GRANT SELECT ON ALL TABLES IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_CLINICIAN;
GRANT SELECT ON ALL TABLES IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_CARE_MGR;
GRANT SELECT ON ALL TABLES IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_CLINICIAN;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_CARE_MGR;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CARELENS.GOLD TO ROLE CARELENS_ANALYST;

/* ---- answer audit trail ------------------------------------------------- */
CREATE OR REPLACE TABLE COPILOT_AUDIT_LOG (
  audit_id STRING DEFAULT UUID_STRING(),
  asked_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  asked_by STRING DEFAULT CURRENT_USER(),
  asked_role STRING DEFAULT CURRENT_ROLE(),
  question STRING, answer STRING,
  tools_used ARRAY, citations ARRAY,
  patient_context STRING, grounded BOOLEAN, latency_ms NUMBER);

CREATE OR REPLACE VIEW V_GROUNDING_SCORECARD AS
SELECT asked_at::DATE AS day, asked_role, COUNT(*) AS answers,
       COUNT_IF(grounded) AS grounded_answers,
       ROUND(100.0 * DIV0(COUNT_IF(grounded), COUNT(*)), 1) AS grounded_pct,
       ROUND(AVG(ARRAY_SIZE(citations)), 2) AS avg_citations_per_answer,
       ROUND(AVG(latency_ms)) AS avg_latency_ms
FROM COPILOT_AUDIT_LOG GROUP BY 1,2 ORDER BY 1 DESC;

/* ---- proof, not assertion: same query, three roles --------------------- */
SELECT ref_entity_name, ref_column_name, policy_kind, policy_name
FROM TABLE(CARELENS.INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'CARELENS.GOLD.PATIENT_360', REF_ENTITY_DOMAIN => 'TABLE'));

/* Run these three by hand during the demo. Same statement, different output.
USE ROLE CARELENS_CLINICIAN; SELECT patient_id, full_name, birth_date, postal_code FROM CARELENS.GOLD.PATIENT_360 LIMIT 3;
USE ROLE CARELENS_CARE_MGR;  SELECT patient_id, full_name, birth_date, postal_code FROM CARELENS.GOLD.PATIENT_360 LIMIT 3;
USE ROLE CARELENS_ANALYST;   SELECT patient_id, full_name, birth_date, postal_code FROM CARELENS.GOLD.PATIENT_360 LIMIT 3;
*/
